# The goal of this file is to get a development deployment running with
# containers so that the feature specs can run.
version: "3.3"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.serve
    ports:
    - "8080:80"
    networks:
    - frontend
    - backend
    depends_on:
    - docs

  features:
    build:
      context: ./features
      dockerfile: support/Dockerfile
    networks:
    - frontend
    depends_on:
    - web
    environment:
      APP_URL: http://web:80

  docs:
    build:
      context: .
      dockerfile: docs/matts-list.com/Dockerfile
    ports:
    - "8081:80"
    networks:
    - frontend

networks:
  frontend: {}
  backend: {}
