# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # GitHub
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Single-page app
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"

  # nginx containerfile for dev purposes
  - package-ecosystem: "docker"
    directory: "/docs/matts-list.com"
    schedule:
      interval: "daily"
