# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"

  # The acceptance tests' support directory has a Dockerfile and
  # a Gemfile.
  - package-ecosystem: "docker"
    directory: "/features/support"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
  - package-ecosystem: "bundler"
    directory: "/features/support"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"

  # My static app is in the web directory and has a couple Dockerfiles
  # as well as package.json and yarn.lock.
  - package-ecosystem: "docker"
    directory: "/web"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/web"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"

  # There's another static website, but it's just regular html/css, so
  # the only file to watch for versions is the Dockerfile, which is for
  # testing purposes only.
  - package-ecosystem: "docker"
    directory: "/docs/matts-list.com"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
