name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-suite:
    name: Run suite
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        make-target:
        - test
        - features
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: 'make ${{ matrix.make-target }}'
