name: "tests"

on:
  push:
    branches: ["main"]
  pull_request: null

jobs:
  run-suite:
    name: "run suite"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        make-target: ["test-app"]
    steps:
    - uses: "actions/checkout@v4"
    - name: "run tests"
      run: "make ${{ matrix.make-target }}"
