FROM node:17.7.2

RUN useradd -d /tmp builder

WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN apt-get update \
      && yarn install \
      && mkdir /tmp/node /tmp/node/cache /tmp/node/coverage \
      && chmod -R 1777 /tmp/node \
      && ln -s /tmp/node/cache node_modules/.cache \
      && ln -s /tmp/node/coverage coverage
COPY ./public public/
COPY ./src src/

# If $CI is set, the tests exit after running.
ENV CI="true"

USER builder
CMD npx standard && yarn test --verbose --coverage
